In [203]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [205]:
# Reading the Dataset
dataset = pd.read_csv('CKD.csv')
print(dataset)

           age         bp sg   al   su     rbc        pc         pcc  \
0     2.000000  76.459948  c  3.0  0.0  normal  abnormal  notpresent   
1     3.000000  76.459948  c  2.0  0.0  normal    normal  notpresent   
2     4.000000  76.459948  a  1.0  0.0  normal    normal  notpresent   
3     5.000000  76.459948  d  1.0  0.0  normal    normal  notpresent   
4     5.000000  50.000000  c  0.0  0.0  normal    normal  notpresent   
..         ...        ... ..  ...  ...     ...       ...         ...   
394  51.492308  70.000000  a  0.0  0.0  normal    normal  notpresent   
395  51.492308  70.000000  c  0.0  2.0  normal    normal  notpresent   
396  51.492308  70.000000  c  3.0  0.0  normal    normal  notpresent   
397  51.492308  90.000000  a  0.0  0.0  normal    normal  notpresent   
398  51.492308  80.000000  a  0.0  0.0  normal    normal  notpresent   

             ba         bgr  ...        pcv            wc        rc  htn   dm  \
0    notpresent  148.112676  ...  38.868902   8408.191

In [207]:
print(dataset.columns)

Index(['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu',
       'sc', 'sod', 'pot', 'hrmo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane', 'classification'],
      dtype='object')


In [209]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [211]:
print(dataset)

           age         bp   al   su         bgr          bu        sc  \
0     2.000000  76.459948  3.0  0.0  148.112676   57.482105  3.077356   
1     3.000000  76.459948  2.0  0.0  148.112676   22.000000  0.700000   
2     4.000000  76.459948  1.0  0.0   99.000000   23.000000  0.600000   
3     5.000000  76.459948  1.0  0.0  148.112676   16.000000  0.700000   
4     5.000000  50.000000  0.0  0.0  148.112676   25.000000  0.600000   
..         ...        ...  ...  ...         ...         ...       ...   
394  51.492308  70.000000  0.0  0.0  219.000000   36.000000  1.300000   
395  51.492308  70.000000  0.0  2.0  220.000000   68.000000  2.800000   
396  51.492308  70.000000  3.0  0.0  110.000000  115.000000  6.000000   
397  51.492308  90.000000  0.0  0.0  207.000000   80.000000  6.800000   
398  51.492308  80.000000  0.0  0.0  100.000000   49.000000  1.000000   

            sod       pot       hrmo  ...  pc_normal  pcc_present  ba_present  \
0    137.528754  4.627244  12.518156  ... 

In [213]:
print(dataset.columns)

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')


In [215]:
# Separate features and target
independent = dataset.drop("classification_yes", axis=1)
dependent = dataset["classification_yes"]

In [217]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(independent, dependent, test_size = 1/3, random_state = 0)

In [219]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

In [221]:
print(X_train_sc)

[[ 0.48681432  1.79924415 -0.68384276 ...  0.51639778 -0.52223297
  -0.44519456]
 [ 0.30305399  0.26080096 -0.68384276 ...  0.51639778 -0.52223297
  -0.44519456]
 [-0.61574769 -0.50842064 -0.68384276 ...  0.51639778 -0.52223297
  -0.44519456]
 ...
 [-0.43198735  0.26080096 -0.68384276 ...  0.51639778 -0.52223297
  -0.44519456]
 [-1.35078903  0.26080096 -0.68384276 ...  0.51639778 -0.52223297
  -0.44519456]
 [-0.06446668 -1.27764223 -0.68384276 ...  0.51639778 -0.52223297
  -0.44519456]]


In [223]:
print(X_test_sc)

[[-0.37073391 -0.50842064 -0.68384276 ...  0.51639778 -0.52223297
  -0.44519456]
 [ 0.85433499  1.03002255  0.94028379 ... -1.93649167 -0.52223297
  -0.44519456]
 [ 1.03809533 -0.50842064 -0.68384276 ...  0.51639778 -0.52223297
  -0.44519456]
 ...
 [-0.24822702  1.79924415 -0.68384276 ... -1.93649167 -0.52223297
  -0.44519456]
 [-0.03431114 -1.27764223  1.75234707 ...  0.51639778 -0.52223297
  -0.44519456]
 [-1.10577525 -1.27764223 -0.68384276 ...  0.51639778 -0.52223297
  -0.44519456]]


In [225]:
print(X_train_sc.shape)

(266, 27)


In [227]:
print(X_test_sc.shape)

(133, 27)


In [229]:
# Standard scalar applied non tree based models
# Logistic Regression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV

param_grid = {"solver": ["newton-cg", "lbfgs", "liblinear", "saga"],
    "penalty": ["l2", "l1", "elasticnet", "none"],
    "C": [1e-4, 1e-3, 1e-2, 1e-1, 1.0, 10.0, 100.0],
    "l1_ratio": [0.0, 0.25, 0.5, 0.75, 1.0],   # only used when penalty='elasticnet'
    "class_weight": [None, "balanced"]} 

grid = GridSearchCV(LogisticRegression(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
   
# fitting the model for grid search 
grid.fit(X_train_sc, y_train) 

Fitting 5 folds for each of 1120 candidates, totalling 5600 fits


C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning: 
3150 fits failed out of a total of 5600.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
350 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1194, in fit
    solver = 

GridSearchCV(estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [0.0001, 0.001, 0.01, 0.1, 1.0, 10.0, 100.0],
                         'class_weight': [None, 'balanced'],
                         'l1_ratio': [0.0, 0.25, 0.5, 0.75, 1.0],
                         'penalty': ['l2', 'l1', 'elasticnet', 'none'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'saga']},
             scoring='f1_weighted', verbose=3)

In [230]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test_sc) 
   
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)

# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [231]:
print(cm)

[[51  0]
 [ 1 81]]


In [237]:
print(clf_report)

              precision    recall  f1-score   support

       False       0.98      1.00      0.99        51
        True       1.00      0.99      0.99        82

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133



In [239]:
from sklearn.metrics import roc_auc_score
from sklearn.metrics import f1_score
model_name = "Logistic Regression -Classification"
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
roc_auc= roc_auc_score(y_test,grid.predict_proba(X_test_sc)[:,1])
print(f"************ Model Score and Classification report for this model: {model_name}***************")
print(cm)
print(clf_report)
print("ROC-AUC Score:", roc_auc)
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

************ Model Score and Classification report for this model: Logistic Regression -Classification***************
[[51  0]
 [ 1 81]]
              precision    recall  f1-score   support

       False       0.98      1.00      0.99        51
        True       1.00      0.99      0.99        82

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133

ROC-AUC Score: 1.0
The f1_macro value for best parameter {'C': 0.1, 'class_weight': None, 'l1_ratio': 0.25, 'penalty': 'elasticnet', 'solver': 'saga'}: 0.9924946382275899


In [145]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test,grid.predict_proba(X_test_sc)[:,1])

1.0

In [135]:
table=pd.DataFrame.from_dict(re)

In [137]:
print(table)

      mean_fit_time  std_fit_time  mean_score_time  std_score_time   param_C  \
0          0.046294      0.022766         0.005266        0.003327    0.0001   
1          0.015661      0.004253         0.010936        0.001075    0.0001   
2          0.006182      0.005055         0.007505        0.005001    0.0001   
3          0.020223      0.003870         0.001397        0.001749    0.0001   
4          0.002815      0.003928         0.000000        0.000000    0.0001   
...             ...           ...              ...             ...       ...   
1115       0.049909      0.007825         0.007517        0.000666  100.0000   
1116       0.001869      0.000866         0.000000        0.000000  100.0000   
1117       0.002038      0.001626         0.000000        0.000000  100.0000   
1118       0.002059      0.001063         0.000000        0.000000  100.0000   
1119       0.001777      0.000286         0.000000        0.000000  100.0000   

     param_class_weight  param_l1_ratio

In [139]:
#GridSearch Hyper Tunining param grid for KNeightbors Classifier
from sklearn.neighbors import KNeighborsClassifier
param_grid = {
    'n_neighbors': [5, 7, 11, 15],
    'weights': ['uniform', 'distance'],
    'metric': ['euclidean','minkowski','manhattan'],
    'algorithm': ['auto', 'ball_tree', 'kd_tree'],
    'p': [1, 2, 3],
    'leaf_size': [20, 30, 40]
} 

grid = GridSearchCV(KNeighborsClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
   
# fitting the model for grid search 
grid.fit(X_train_sc, y_train) 

Fitting 5 folds for each of 648 candidates, totalling 3240 fits


C:\Users\DELL\anaconda3\Lib\site-packages\numpy\ma\core.py:2820: RuntimeWarning: invalid value encountered in cast
  _data = np.array(data, dtype=dtype, copy=copy,


GridSearchCV(estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree'],
                         'leaf_size': [20, 30, 40],
                         'metric': ['euclidean', 'minkowski', 'manhattan'],
                         'n_neighbors': [5, 7, 11, 15], 'p': [1, 2, 3],
                         'weights': ['uniform', 'distance']},
             scoring='f1_weighted', verbose=3)

In [141]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test_sc) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)

# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)


In [143]:
print(cm)
print(clf_report)

[[51  0]
 [ 9 73]]
              precision    recall  f1-score   support

       False       0.85      1.00      0.92        51
        True       1.00      0.89      0.94        82

    accuracy                           0.93       133
   macro avg       0.93      0.95      0.93       133
weighted avg       0.94      0.93      0.93       133



In [147]:
from sklearn.metrics import roc_auc_score
from sklearn.metrics import f1_score
model_name = "KNeighborsClassifier"
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
roc_auc= roc_auc_score(y_test,grid.predict_proba(X_test_sc)[:,1])
print(f"************ Model Score and Classification report for this model: {model_name}***************")
print(cm)
print(clf_report)
print("ROC-AUC Score:", roc_auc)
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

************ Model Score and Classification report for this model: KNeighborsClassifier***************
[[51  0]
 [ 9 73]]
              precision    recall  f1-score   support

       False       0.85      1.00      0.92        51
        True       1.00      0.89      0.94        82

    accuracy                           0.93       133
   macro avg       0.93      0.95      0.93       133
weighted avg       0.94      0.93      0.93       133

ROC-AUC Score: 1.0
The f1_macro value for best parameter {'algorithm': 'auto', 'leaf_size': 20, 'metric': 'minkowski', 'n_neighbors': 5, 'p': 3, 'weights': 'distance'}: 0.9331095830246934


In [149]:
model_name = "SVM Classification"
#GridSearch Hyper Tunining param grid for KNeightbors Classifier
from sklearn.svm import SVC
param_grid = {
        'kernel': ['linear', 'rbf', 'poly', 'sigmoid'],  # unified kernel array
        'C': [0.01, 0.1, 1, 10, 100],
        'gamma': ['scale', 'auto', 0.001, 0.01, 0.1, 1],
        'class_weight': [None, 'balanced']
    }

grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
   
# fitting the model for grid search 
grid.fit(X_train_sc, y_train) 

Fitting 5 folds for each of 240 candidates, totalling 1200 fits


GridSearchCV(estimator=SVC(), n_jobs=-1,
             param_grid={'C': [0.01, 0.1, 1, 10, 100],
                         'class_weight': [None, 'balanced'],
                         'gamma': ['scale', 'auto', 0.001, 0.01, 0.1, 1],
                         'kernel': ['linear', 'rbf', 'poly', 'sigmoid']},
             scoring='f1_weighted', verbose=3)

In [151]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test_sc) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)

# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [153]:
from sklearn.metrics import roc_auc_score
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
roc_auc= roc_auc_score(y_test,grid.decision_function(X_test_sc))
print(f"************ Model Score and Classification report for this model: {model_name}***************")
print(cm)
print(clf_report)
print("ROC-AUC Score:", roc_auc)
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

************ Model Score and Classification report for this model: SVM Classification***************
[[51  0]
 [ 3 79]]
              precision    recall  f1-score   support

       False       0.94      1.00      0.97        51
        True       1.00      0.96      0.98        82

    accuracy                           0.98       133
   macro avg       0.97      0.98      0.98       133
weighted avg       0.98      0.98      0.98       133

ROC-AUC Score: 1.0
The f1_macro value for best parameter {'C': 1, 'class_weight': 'balanced', 'gamma': 'scale', 'kernel': 'linear'}: 0.9775556904684072


In [155]:
model_name = "Naive Bayes - GaussianNB"
#GridSearch Hyper Tunining param grid for GaussianNB
from sklearn.naive_bayes import GaussianNB
param_grid = {
        'var_smoothing': np.logspace(-12, -6, 13)
    }

grid = GridSearchCV(GaussianNB(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
   
# fitting the model for grid search 
grid.fit(X_train_sc, y_train) 

Fitting 5 folds for each of 13 candidates, totalling 65 fits


GridSearchCV(estimator=GaussianNB(), n_jobs=-1,
             param_grid={'var_smoothing': array([1.00000000e-12, 3.16227766e-12, 1.00000000e-11, 3.16227766e-11,
       1.00000000e-10, 3.16227766e-10, 1.00000000e-09, 3.16227766e-09,
       1.00000000e-08, 3.16227766e-08, 1.00000000e-07, 3.16227766e-07,
       1.00000000e-06])},
             scoring='f1_weighted', verbose=3)

In [157]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test_sc) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)

# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [159]:
from sklearn.metrics import roc_auc_score
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
roc_auc= roc_auc_score(y_test,grid.predict_proba(X_test_sc)[:,1])
print(f"************ Model Score and Classification report for this model: {model_name}***************")
print(cm)
print(clf_report)
print("ROC-AUC Score:", roc_auc)
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

************ Model Score and Classification report for this model: Naive Bayes - GaussianNB***************
[[51  0]
 [ 3 79]]
              precision    recall  f1-score   support

       False       0.94      1.00      0.97        51
        True       1.00      0.96      0.98        82

    accuracy                           0.98       133
   macro avg       0.97      0.98      0.98       133
weighted avg       0.98      0.98      0.98       133

ROC-AUC Score: 1.0
The f1_macro value for best parameter {'var_smoothing': 1e-08}: 0.9775556904684072


In [161]:
model_name = "Naive Bayes - MultinomialNB"
#GridSearch Hyper Tunining param grid for GaussianNB without Standard Scalar
from sklearn.naive_bayes import MultinomialNB
param_grid = {
        'alpha': np.logspace(-4, 1, 10),
        'fit_prior': [True, False]
    }

grid = GridSearchCV(MultinomialNB(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
   
# fitting the model for grid search 
grid.fit(X_train, y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits


GridSearchCV(estimator=MultinomialNB(), n_jobs=-1,
             param_grid={'alpha': array([1.00000000e-04, 3.59381366e-04, 1.29154967e-03, 4.64158883e-03,
       1.66810054e-02, 5.99484250e-02, 2.15443469e-01, 7.74263683e-01,
       2.78255940e+00, 1.00000000e+01]),
                         'fit_prior': [True, False]},
             scoring='f1_weighted', verbose=3)

In [163]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)

# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [165]:
from sklearn.metrics import roc_auc_score
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
roc_auc= roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])
print(f"************ Model Score and Classification report for this model: {model_name}***************")
print(cm)
print(clf_report)
print("ROC-AUC Score:", roc_auc)
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

************ Model Score and Classification report for this model: Naive Bayes - MultinomialNB***************
[[50  1]
 [ 8 74]]
              precision    recall  f1-score   support

       False       0.86      0.98      0.92        51
        True       0.99      0.90      0.94        82

    accuracy                           0.93       133
   macro avg       0.92      0.94      0.93       133
weighted avg       0.94      0.93      0.93       133

ROC-AUC Score: 0.9612625538020085
The f1_macro value for best parameter {'alpha': 0.0001, 'fit_prior': True}: 0.9329951419775407


In [169]:
model_name = "Naive Bayes - Bernouli"
#GridSearch Hyper Tunining param grid for GaussianNB without Standard Scalar
from sklearn.naive_bayes import BernoulliNB
param_grid = {
        'alpha': np.logspace(-4, 1, 10),
        'fit_prior': [True, False]
    }

grid = GridSearchCV(BernoulliNB(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
   
# fitting the model for grid search 
grid.fit(X_train_sc, y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits


GridSearchCV(estimator=BernoulliNB(), n_jobs=-1,
             param_grid={'alpha': array([1.00000000e-04, 3.59381366e-04, 1.29154967e-03, 4.64158883e-03,
       1.66810054e-02, 5.99484250e-02, 2.15443469e-01, 7.74263683e-01,
       2.78255940e+00, 1.00000000e+01]),
                         'fit_prior': [True, False]},
             scoring='f1_weighted', verbose=3)

In [171]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test_sc) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)

# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [173]:
from sklearn.metrics import roc_auc_score
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
roc_auc= roc_auc_score(y_test,grid.predict_proba(X_test_sc)[:,1])
print(f"************ Model Score and Classification report for this model: {model_name}***************")
print(cm)
print(clf_report)
print("ROC-AUC Score:", roc_auc)
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

************ Model Score and Classification report for this model: Naive Bayes - Bernouli***************
[[51  0]
 [ 2 80]]
              precision    recall  f1-score   support

       False       0.96      1.00      0.98        51
        True       1.00      0.98      0.99        82

    accuracy                           0.98       133
   macro avg       0.98      0.99      0.98       133
weighted avg       0.99      0.98      0.99       133

ROC-AUC Score: 1.0
The f1_macro value for best parameter {'alpha': 0.0001, 'fit_prior': True}: 0.9850141736106648


In [177]:
model_name = "Naive Bayes - ComplementNB"
#GridSearch Hyper Tunining param grid for GaussianNB without Standard Scalar
from sklearn.naive_bayes import ComplementNB
param_grid = {
        'alpha': np.logspace(-4, 1, 10),
        'norm': [True, False]
    }

grid = GridSearchCV(ComplementNB(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
   
# fitting the model for grid search 
grid.fit(X_train, y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits


GridSearchCV(estimator=ComplementNB(), n_jobs=-1,
             param_grid={'alpha': array([1.00000000e-04, 3.59381366e-04, 1.29154967e-03, 4.64158883e-03,
       1.66810054e-02, 5.99484250e-02, 2.15443469e-01, 7.74263683e-01,
       2.78255940e+00, 1.00000000e+01]),
                         'norm': [True, False]},
             scoring='f1_weighted', verbose=3)

In [179]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)

# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [181]:
from sklearn.metrics import roc_auc_score
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
roc_auc= roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])
print(f"************ Model Score and Classification report for this model: {model_name}***************")
print(cm)
print(clf_report)
print("ROC-AUC Score:", roc_auc)
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

************ Model Score and Classification report for this model: Naive Bayes - ComplementNB***************
[[50  1]
 [ 8 74]]
              precision    recall  f1-score   support

       False       0.86      0.98      0.92        51
        True       0.99      0.90      0.94        82

    accuracy                           0.93       133
   macro avg       0.92      0.94      0.93       133
weighted avg       0.94      0.93      0.93       133

ROC-AUC Score: 0.9612625538020085
The f1_macro value for best parameter {'alpha': 0.0001, 'norm': False}: 0.9329951419775407


In [185]:
model_name = "Decision Tree"
#GridSearch Hyper Tunining param grid for GaussianNB without Standard Scalar
from sklearn.tree import DecisionTreeClassifier
param_grid = {
    'criterion': ['gini', 'entropy', 'log_loss'],
    'max_depth': [5, 10, 20, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'ccp_alpha': [0.0, 0.001, 0.01]
    }

grid = GridSearchCV(DecisionTreeClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
   
# fitting the model for grid search 
grid.fit(X_train, y_train)

Fitting 5 folds for each of 324 candidates, totalling 1620 fits


C:\Users\DELL\anaconda3\Lib\site-packages\numpy\ma\core.py:2820: RuntimeWarning: invalid value encountered in cast
  _data = np.array(data, dtype=dtype, copy=copy,


GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'ccp_alpha': [0.0, 0.001, 0.01],
                         'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_depth': [5, 10, 20, None],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10]},
             scoring='f1_weighted', verbose=3)

In [187]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)

# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [189]:
from sklearn.metrics import roc_auc_score
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
roc_auc= roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])
print(f"************ Model Score and Classification report for this model: {model_name}***************")
print(cm)
print(clf_report)
print("ROC-AUC Score:", roc_auc)
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

************ Model Score and Classification report for this model: Decision Tree***************
[[50  1]
 [ 9 73]]
              precision    recall  f1-score   support

       False       0.85      0.98      0.91        51
        True       0.99      0.89      0.94        82

    accuracy                           0.92       133
   macro avg       0.92      0.94      0.92       133
weighted avg       0.93      0.92      0.93       133

ROC-AUC Score: 0.9353180296508847
The f1_macro value for best parameter {'ccp_alpha': 0.0, 'criterion': 'gini', 'max_depth': 5, 'min_samples_leaf': 1, 'min_samples_split': 5}: 0.925618241407715


In [191]:
model_name = "Random Forest"
#GridSearch Hyper Tunining param grid for GaussianNB without Standard Scalar
from sklearn.ensemble import RandomForestClassifier
param_grid = {
    'n_estimators': [200, 500],
    'max_depth': [10, 20, None],
    'min_samples_leaf': [1, 2, 5],
    'class_weight': [None, 'balanced', 'balanced_subsample'],
    'max_features': ['sqrt', 'log2'],
    'criterion': ['gini', 'entropy']
    }

grid = GridSearchCV(RandomForestClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
   
# fitting the model for grid search 
grid.fit(X_train, y_train)

Fitting 5 folds for each of 216 candidates, totalling 1080 fits


GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'class_weight': [None, 'balanced',
                                          'balanced_subsample'],
                         'criterion': ['gini', 'entropy'],
                         'max_depth': [10, 20, None],
                         'max_features': ['sqrt', 'log2'],
                         'min_samples_leaf': [1, 2, 5],
                         'n_estimators': [200, 500]},
             scoring='f1_weighted', verbose=3)

In [199]:
from sklearn.metrics import roc_auc_score
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
roc_auc= roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])
print(f"************ Model Score and Classification report for this model: {model_name}***************")
print(cm)
print(clf_report)
print("ROC-AUC Score:", roc_auc)
print("\n")
print("The f1_macro value for best parameter {}:".format(grid.best_params_))
print("The f1_macro value:",f1_macro)

************ Model Score and Classification report for this model: Random Forest***************
[[50  1]
 [ 9 73]]
              precision    recall  f1-score   support

       False       0.85      0.98      0.91        51
        True       0.99      0.89      0.94        82

    accuracy                           0.92       133
   macro avg       0.92      0.94      0.92       133
weighted avg       0.93      0.92      0.93       133

ROC-AUC Score: 0.9997608799617408


The f1_macro value for best parameter {'class_weight': None, 'criterion': 'gini', 'max_depth': 10, 'max_features': 'log2', 'min_samples_leaf': 1, 'n_estimators': 500}:
The f1_macro value: 0.925618241407715
